fix(web): Set jest rootDir = src (#1801)
* fix(web): Set jest testURL to fix opaque origin

This fixes the following error that I get when running `npm run test`:

```
 FAIL  src/utils/__tests__/composeThemeObject.js
  ● Test suite failed to run

    SecurityError: localStorage is not available for opaque origins

      at Window.get localStorage [as localStorage] (node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
          at Array.forEach (<anonymous>)
```

* fix(web): Set jest rootDir = src

so we don't run tests on files in both `src` and `lib`. For example, I
created a new file, `SingleDataList.spec.js` in `src` and it got copied
to `lib` with the build and then Jest wanted to run on both copies of
the file, which seems redundant:

```
 PASS  src/components/list/SingleDataList.spec.js
 PASS  lib/components/list/SingleDataList.spec.js
 PASS  src/utils/__tests__/composeThemeObject.js

Test Suites: 3 passed, 3 total
Tests:       4 passed, 4 total
Snapshots:   0 total
Time:        0.123s, estimated 1s
Ran all test suites.
```